### ISSUE TITLE
How to use this in REST API

### ISSUE THREAD

**Issue by chavan92** [TierMobility/tile38-ts#174]
I'm building an application that uses REST api. I'm able to setup fences. One of the API that will be used the most, calls set().
wondering what is the right way to use tile38 in this rest api.

Approaches, I'm considering:
1. create a new Tile38 class object in the api and call the set function.

2. create a singleton class and use the instance of it globally to call any Tile38 function

Observations:
With approach 1, it creates a new object and connection on every request. I tried calling quit() after the set() call, the first request goes through and then it closes all the connections and starts throwing this error:
error: ClientClosedError: The client is closed

with approach 2 everything looks fine, but my concern is with multithreading as single object will be shared in multiple simultaneous requests of the API and it might run into a problem.

Very new to redis and tile38, could you please suggest what should be the right approach here?

PS: great job with this project, very well documented and rich code quality. cheers to the team! :)

**Comment by chavan92** [comment]
Whoops, my bad! I was calling 
tile38.set(..).point(..).exec()
tile38.quit()

so probably it was closing the connection before finishing the call.

I changed it to be called after finishing exec().
tile38.set(..).point(..).exec().finally(() => tile38.quit())
it works now.

going with approach 1, as it ensures api being stateless . although, let me know if you have any other ideas.

Thanks.

**Comment by iwpnd** [comment]
You can just use instantiate it somewhere and import it - let node-redis take care of your connection (connect, reconnect).

```typescript
import { Tile38 } from '@tiermobility/tile38-ts';

export const tile38 = new Tile38().on('error', (error) =>
    your_logger.error('An error occurred:', error)
);
```

Make sure you handle shutdown gracefully and quit tile38 in your express application.

**Comment by chavan92** [comment]
Thank you for your reply. Just to confirm, what you are suggesting is to create only one object for the application and share it between all the APIs

I was thinking creating  a singleton class (its the same thing what you are doing, just becomes easy to add some custom actions):

```
export class MyClass extends Tile38 {

  private static instance: MyClass = null

  public constructor(url:string) {
    super(url)
  }

  public static getInstance() {
    if(!this.instance) {
      this.instance = new MyClass(..).on('error', (error) =>
      logger.error('An error occurred:', error)
    }

    return this.instance
  }
}

```

On the API side:

```
public function Api() {
  MyClass.getInstance().set(..).point(..).exec()
}

```

do you think there are any side effects in case of simultaneous multiple API calls as all API calls will be sharing single instance?

**Comment by iwpnd** [comment]
Tile38 is already a singleton, [see](https://github.com/TierMobility/tile38-ts/blob/main/src/Client.ts#L98). If I'm not mistaken then node-redis has an internal queue to prohibited the behaviour you're worried about.

**Comment by chavan92** [comment]
I just looked around and found that redis is thread safe and has internal connection pool, as you said.
 It is clear for me now. Thanks!

**Comment by iwpnd** [comment]
Glad you found your answers. 🙏
